# Generated by Django 2.0.7 on 2018-07-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('summary', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Home',
        ),
    ]
