# Generated by Django 2.0.7 on 2018-07-09 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garrely', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Garrely',
            new_name='Photos',
        ),
    ]
