# Generated by Django 2.0.7 on 2018-07-09 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garrely', '0002_auto_20180709_1712'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photos',
            new_name='Photo',
        ),
    ]
